export default function OutlierMatrix() {
    return (
        <table className='similarity-matrix'>
            <tbody>
                <tr>
                    <th></th>
                    <th>fr</th>
                    <th>es</th>
                    <th>de</th>
                    <th>zh</th>
                    <th>ja</th>
                    <th>ru</th>
                    <th>pt</th>
                    <th>en</th>
                </tr>
                <tr>
                    <td><strong>fr</strong></td>
                    <td>27788</td>
                    <td>90</td>
                    <td>51</td>
                    <td>13</td>
                    <td>5</td>
                    <td>7</td>
                    <td>57</td>
                    <td>432</td>
                </tr>
                <tr>
                    <td><strong>es</strong></td>
                    <td>86</td>
                    <td>26284</td>
                    <td>14</td>
                    <td>18</td>
                    <td>5</td>
                    <td>2</td>
                    <td>704</td>
                    <td>330</td>
                </tr>
                <tr>
                    <td><strong>de</strong></td>
                    <td>52</td>
                    <td>21</td>
                    <td>30036</td>
                    <td>3</td>
                    <td>8</td>
                    <td>2</td>
                    <td>7</td>
                    <td>429</td>
                </tr>
                <tr>
                    <td><strong>zh</strong></td>
                    <td>9</td>
                    <td>16</td>
                    <td>5</td>
                    <td>35877</td>
                    <td>668</td>
                    <td>21</td>
                    <td>3</td>
                    <td>110</td>
                </tr>
                <tr>
                    <td><strong>ja</strong></td>
                    <td>3</td>
                    <td>4</td>
                    <td>3</td>
                    <td>434</td>
                    <td>40905</td>
                    <td>3</td>
                    <td>2</td>
                    <td>27</td>
                </tr>
                <tr>
                    <td><strong>ru</strong></td>
                    <td>0</td>
                    <td>1</td>
                    <td>0</td>
                    <td>12</td>
                    <td>3</td>
                    <td>42016</td>
                    <td>1</td>
                    <td>35</td>
                </tr>
                <tr>
                    <td><strong>pt</strong></td>
                    <td>59</td>
                    <td>655</td>
                    <td>11</td>
                    <td>5</td>
                    <td>2</td>
                    <td>4</td>
                    <td>27793</td>
                    <td>205</td>
                </tr>
                <tr>
                    <td><strong>en</strong></td>
                    <td>249</td>
                    <td>222</td>
                    <td>254</td>
                    <td>51</td>
                    <td>19</td>
                    <td>6</td>
                    <td>120</td>
                    <td>17365</td>
                </tr>
            </tbody>
        </table>
    );
}
